# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: E-mentoring
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://qudwa.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

defaults:
  - scope:
      path: ""
      type: mentors
    values:
      layout: mentor

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  mentors:
    output: true
    permalink: /:categories/:name
  mentor_posts:
    output: false

languages:
  - name: 'English'
    key: 'en'
  - name: 'Arabic'
    key: 'ar'

# Prose settings
prose:
  ignore:
    - .vscode
    - _data
    - _includes
    - _layouts
    - _posts
    - _sass
    - _site
    - ar
    - _assets
    - en
    - js
    - _config.yml
    - 404.html
    - about.md
    - Gemfile
    - Gemfile.lock
    - .gitignore
    - index.html
    - LICENSE.txt
    - mentors.ar.js
    - mentors.en.js
    - README.md
  media: "media"
  metadata:
    _mentors/arabic:
      - name: "ref"
        field:
          element: "text"
          label: Reference
      - name: "name"
        field:
          element: "text"
          label: Name
      - name: "image"
        field:
          element: "text"
          label: Image
      - name: "tags"
        field:
          element: "multiselect"
          label: Tags
          alterable: true
      - name: "jobtitle"
        field:
          element: "text"
          label: Job Title
      - name: "workplace"
        field:
          element: "text"
          label: Workplace
      - name: "shortbio"
        field:
          element: "textarea"
          label: Short Bio
      - name: "longbio"
        field:
          element: "textarea"
          label: Long Bio
      - name: "lang"
        field:
          element: "hidden"
          value: "ar"
      - name: "categories"
        field:
          element: "hidden"
          value: "ar"
      - name: "topics"
        field:
          element: "multiselect"
          label: Topics
          alterable: true
      - name: "interests"
        field:
          element: "multiselect"
          label: Interests
          alterable: true
    _mentors/english:
      - name: "ref"
        field:
          element: "text"
          label: Reference
      - name: "name"
        field:
          element: "text"
          label: Name
      - name: "image"
        field:
          element: "text"
          label: Image
      - name: "tags"
        field:
          element: "multiselect"
          label: Tags
          alterable: true
      - name: "jobtitle"
        field:
          element: "text"
          label: Job Title
      - name: "workplace"
        field:
          element: "text"
          label: Workplace
      - name: "shortbio"
        field:
          element: "textarea"
          label: Short Bio
      - name: "longbio"
        field:
          element: "textarea"
          label: Long Bio
      - name: "lang"
        field:
          element: "hidden"
          value: "en"
      - name: "categories"
        field:
          element: "hidden"
          value: "en"
      - name: "topics"
        field:
          element: "multiselect"
          label: Topics
          alterable: true
      - name: "interests"
        field:
          element: "multiselect"
          label: Interests
          alterable: true
  

  #rooturl: '_mentors'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
